### conda env create -f environment.yml
name: emoreasenv
channels:
  # - pytorch
  # - kumatea
  - conda-forge
dependencies:
  - python
  - jupyterlab
  - autopep8
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - statsmodels
  - matplotlib
  - seaborn
  - pytorch
  - conda-lock
  # - kumatea::numpy
  # - kumatea::pytorch
  - pip
platforms:
  - linux-aarch64
